### ISSUE TITLE
Update `action-fuel-toolchain` to v0.2.0 in CI 

### ISSUE THREAD

**Issue by bingcicle** [FuelLabs/sway-applications#199]
Once these PRs are merged and new versions are released, the CI should be able to 'freeze' component versions in the toolchain.

https://github.com/FuelLabs/action-fuel-toolchain/pull/72
https://github.com/FuelLabs/fuelup/pull/131

We can do something like:

```yaml
- name: Install Fuel toolchain
  uses: FuelLabs/action-fuel-toolchain@v0.2.0
  with:
    name: my-toolchain
    components: forc@0.19.2, fuel-core@0.10.1
```
